/*
 * Created by v1tr10l7 on 04.07.2025.
 * Copyright (c) 2024-2025, Szymon Zemke <v1tr10l7@proton.me>
 *
 * SPDX-License-Identifier: GPL-3
 */
#pragma once

namespace ACPI
{
    enum class OpCode : u16
    {
        eZero             = 0x00,
        eOne              = 0x01,
        eAlias            = 0x06,
        eName             = 0x08,
        eBytePrefix       = 0x0a,
        eWordPrefix       = 0x0b,
        eDWordPrefix      = 0x0c,
        eStringPrefix     = 0x0d,
        eQWordPrefix      = 0x0e,
        eScope            = 0x10,
        eBuffer           = 0x11,
        ePackage          = 0x12,
        eVarPackage       = 0x13,
        eMethod           = 0x14,
        eExternal         = 0x15,
        eDualNamePrefix   = 0x2e,
        eMultiNamePrefix  = 0x2f,
        eExtOpPrefix      = 0x5b,
        eMutex            = 0x5b01,
        eEvent            = 0x5b02,
        eCondRefOf        = 0x5b12,
        eCreateField      = 0x5b13,
        eLoadTable        = 0x5b1f,
        eLoad             = 0x5b20,
        eStall            = 0x5b21,
        eSleep            = 0x5b22,
        eAcquire          = 0x5b23,
        eSignal           = 0x5b24,
        eWait             = 0x5b25,
        eReset            = 0x5b26,
        eRelease          = 0x5b27,
        eFromBCD          = 0x5b28,
        eToBCD            = 0x5b29,
        eRevision         = 0x5b30,
        eDebug            = 0x5b31,
        eFatal            = 0x5b32,
        eTimer            = 0x5b33,
        eOpRegion         = 0x5b80,
        eField          = 0x5b81,
        eDevice           = 0x5b82,
        ePowerRes         = 0x5b84,
        eThermalZone      = 0x5b85,
        eIndexField       = 0x5b86,
        eBankField        = 0x5b87,
        eDataRegion       = 0x5b88,
        eRootChar         = 0x5c,
        eParentPrefix     = 0x5e,
        eNameChar         = 0x5f,
        eLocal0         = 0x60,
        eLocal1         = 0x61,
        eLocal2         = 0x62,
        eLocal3         = 0x63,
        eLocal4         = 0x64,
        eLocal5         = 0x65,
        eLocal6         = 0x66,
        eLocal7         = 0x67,
        eArg0             = 0x68,
        eArg1             = 0x69,
        eArg2             = 0x6a,
        eArg3             = 0x6b,
        eArg4             = 0x6c,
        eArg5             = 0x6d,
        eArg6             = 0x6e,
        eStore            = 0x70,
        eRefOf            = 0x71,
        eAdd              = 0x72,
        eConcat           = 0x73,
        eSubtract         = 0x74,
        eIncrement        = 0x75,
        eDecrement        = 0x76,
        eMultiply         = 0x77,
        eDivide           = 0x78,
        eShiftLeft        = 0x79,
        eShiftRight       = 0x7a,
        eAnd              = 0x7b,
        eNAnd             = 0x7c,
        eOr               = 0x7d,
        eNOr              = 0x7e,
        eXOr              = 0x7f,
        eNot              = 0x80,
        eFindSetLeftBit   = 0x81,
        eFindSetRightBit  = 0x82,
        eDerefOf          = 0x83,
        eConcatRes        = 0x84,
        eMod              = 0x85,
        eNotify           = 0x86,
        eSizeOf           = 0x87,
        eIndex            = 0x88,
        eMatch            = 0x89,
        eCreateDWordField = 0x8a,
        eCreateWordField  = 0x8b,
        eCreateByteField  = 0x8c,
        eCreateBitField   = 0x8d,
        eObjectType       = 0x8e,
        eCreateQWordField = 0x8f,
        eLAnd             = 0x90,
        eLor              = 0x91,
        eLnot             = 0x92,
        eLnotEqual        = 0x9293,
        eLLessEqual       = 0x9294,
        eLGreaterEqual    = 0x9295,
        eLEqual           = 0x93,
        eLGreater         = 0x94,
        eLLess            = 0x95,
        eToBuffer         = 0x96,
        eToDecimal        = 0x97,
        eToHexString      = 0x98,
        eToInteger        = 0x99,
        eCopyObject       = 0x9d,
        eMid              = 0x9e,
        eContinue         = 0x9f,
        eIf               = 0xa0,
        eElse             = 0xa1,
        eWhile            = 0xa2,
        eNoop             = 0xa3,
        eReturn           = 0xa4,
        eBreak            = 0xa5,
        eBreakPoint       = 0xcc,
        eOnes             = 0xff,
    };
};
