name: CI Meson

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        build-configuration: [release, debug, dist]
        architecture: [x86_64, aarch64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: sudo add-apt-repository -y universe 
          && sudo apt update -y 
          && sudo apt install -y meson ninja-build clang lld llvm git cmake python3 pipx fasm
          && sudo apt install -y build-essential qemu-system parted udev bison flex libgmp3-dev libmpc-dev libmpfr-dev
          && sudo apt install -y texinfo libisl-dev gperf gettext autopoint libreadline-dev help2man groff zsh xorriso bochs qpdf 
          && sudo apt install -y libguestfs-tools guestfs-python libguestfs-dev python3-guestfs python3-venv libguestfs
          && pipx install xbstrap 
      - name: Create /usr/sbin/init
        run: mkdir -p build-sysroot/system-root/usr/sbin/ && touch sysroot/usr/sbin/init
      - name: Configure Project
        run: ./Meta/setup.sh ${{ matrix.architecture }} ${{ matrix.build-configuration }} 
          && (cd subprojects/fmt-10.2.0/ && yes | patch -p 1 < ../../Meta/fmt-10.2.0.patch)
          && ./Meta/build.sh ${{ matrix.architecture }} ${{ matrix.build-configuration }} 
    
